-- 1. Create the table for time blocks
CREATE TABLE IF NOT EXISTS schedule_time_blocks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  schedule_id BIGINT NOT NULL REFERENCES schedules(id) ON DELETE CASCADE,
  start_time TIMESTAMP WITH TIME ZONE NOT NULL,
  end_time TIMESTAMP WITH TIME ZONE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Migrate existing data (1 Schedule = 1 Block)
-- Only insert if the block doesn't exist for that schedule to avoid duplicates on re-run
INSERT INTO schedule_time_blocks (schedule_id, start_time, end_time)
SELECT id, "startDate", "endDate"
FROM schedules
WHERE NOT EXISTS (
    SELECT 1 FROM schedule_time_blocks WHERE schedule_id = schedules.id
);

-- Optional: Create index for performance
CREATE INDEX IF NOT EXISTS idx_schedule_time_blocks_schedule_id ON schedule_time_blocks(schedule_id);
